### ISSUE TITLE
ECR Deploy failing - The process 'aws' failed with exit code 252

### ISSUE THREAD

**Issue by ateev** [Terranovax/aws-ecr-deploy#10]
Hello, I started getting this issue just today and not sure if it's AWS APIs issue or something else. Can someone please help

```
== LOGIN INTO AWS ECR ==
16
(node:1927) UnhandledPromiseRejectionWarning: Error: The process 'aws' failed with exit code 252
17
    at ExecState._setResult (/home/runner/work/_actions/Terranovax/aws-ecr-deploy/v1/dist/index.js:597:25)
18
    at ExecState.CheckComplete (/home/runner/work/_actions/Terranovax/aws-ecr-deploy/v1/dist/index.js:580:18)
19
    at ChildProcess.<anonymous> (/home/runner/work/_actions/Terranovax/aws-ecr-deploy/v1/dist/index.js:480:27)
20
    at ChildProcess.emit (events.js:210:5)
21
    at maybeClose (internal/child_process.js:1021:16)
22
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
23
(node:1927) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
24
(node:1927) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here is my github action
```
# This is a basic workflow to help you get started with Actions

name: ECR Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - v*
env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - uses: actions/checkout@v2
    - uses: Terranovax/aws-ecr-deploy@v1
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        region: ap-south-1
        tags: latest,${{ env.RELEASE_VERSION}}
        repo: web
        create_repo: true
        dockerfile: Dockerfile
```
